
[functions.send-push-notification]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-push-notification/index.ts"

[functions.agora-token]
enabled = true
verify_jwt = false
import_map = "./functions/agora-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/agora-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/agora-token/*.html" ]

[functions.red-packet-reminders]
enabled = true
verify_jwt = false
entrypoint = "./functions/red-packet-reminders/index.ts"
